pool:
  vmImage: 'macos-latest'

variables:
  flutterVersion: '3.5.3'  # Specify the Flutter version tag
  buildConfiguration: 'Release'  # Build configuration (Debug, Release)

steps:
# Install Flutter
- script: |
    git clone --branch $(flutterVersion) https://github.com/flutter/flutter.git
    echo '##vso[task.prependpath]$(Pipeline.Workspace)/flutter/bin'
    export PATH="$(Pipeline.Workspace)/flutter/bin:$PATH"
    flutter doctor
  displayName: 'Install Flutter'

# Clean Previous Builds
- script: flutter clean
  displayName: 'Clean Previous Builds'

# Install Dependencies
- script: flutter pub get
  displayName: 'Install Dependencies'

# Build iOS App Without Signing
- script: |
    flutter build ios --release --no-codesign
  displayName: 'Build iOS App (Unsigned)'
